{% set name = "lockfilesemaphore" %}
{% set version = "3.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81900a030129bc4ec1bf73859497c998c6ab08e15600219e18dc43bb91ba6fb6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - LockFileSemaphore
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/LockFileSemaphore/
  license: BSD-3-Clause OR MIT
  license_file: LICENSE
  summary: Robust file-based semaphore with stale lock recovery and context manager support.

extra:
  recipe-maintainers:
    - Marcin-kowalczyk-polenergia
